export const cityTypes = {
    GET_CITY_AUTOCOMPLETE_REQUEST: "GET_CITY_AUTOCOMPLETE_REQUEST",
    GET_CITY_AUTOCOMPLETE_SUCCESS: "GET_CITY_AUTOCOMPLETE_SUCCESS",
    GET_CITY_AUTOCOMPLETE_FAILURE: "GET_CITY_AUTOCOMPLETE_FAILURE",
    SET_SELECTED_CITY: 'SET_SELECTED_CITY',
    GET_CITY_BY_ID_REQUEST: 'GET_CITY_BY_ID_REQUEST',
    GET_CITY_BY_ID_SUCCESS: 'GET_CITY_BY_ID_SUCCESS',
    GET_CITY_BY_ID_FAILURE: 'GET_CITY_BY_ID_FAILURE',
    GET_CITY_BY_GEOLOCATION_REQUEST: 'GET_CITY_BY_GEOLOCATION_REQUEST',
    GET_CITY_BY_GEOLOCATION_SUCCESS: 'GET_CITY_BY_GEOLOCATION_SUCCESS',
    GET_CITY_BY_GEOLOCATION_FAILURE: 'GET_CITY_BY_GEOLOCATION_FAILURE',
}   