export const weatherTypes = {
    GET_CITY_WEATHER_REQUEST: "GET_CITY_WEATHER_REQUEST",
    GET_CITY_WEATHER_SUCCESS: "GET_CITY_WEATHER_SUCCESS",
    GET_CITY_WEATHER_FAILURE: "GET_CITY_WEATHER_FAILURE",
    SET_UNIT_TEMP: 'SET_UNIT_TEMP'
}